### ISSUE TITLE
Sidebar Disappearing

### ISSUE THREAD

**Issue by taha-azzan** [frappe/wiki#103]
Hi Frappe Team,

I have a problem that the sidebar suddenly disappears when I open the wiki page, as shown in the picture below:
![Wiki Issue](https://user-images.githubusercontent.com/67021079/200378128-2ac7cf93-dc36-4eb4-b48f-ea1ca27120f9.gif)

Thank you in advance

**Comment by BreadGenie** [comment]
Can you replicate this issue with the latest wiki version?

**Comment by BreadGenie** [comment]
I wasn't able to reproduce the issue. Feel free to reopen if the issue persists.
