### ISSUE TITLE
Wiki Page attachments are not fetched on further edits

### ISSUE THREAD

**Issue by parameshnalla** [frappe/wiki#118]
While trying to store attachments to an existing wiki, attachment upload is successful but attached files are not visible anywhere in the wiki. 

![Screen Shot 2023-01-24 at 11 48 57 PM](https://user-images.githubusercontent.com/7420632/214482814-feba4a9c-bc6b-49fe-a857-685b85befb52.png)
![Screen Shot 2023-01-24 at 11 49 12 PM](https://user-images.githubusercontent.com/7420632/214482817-27079f7c-94e8-42f3-9eff-8934665b8002.png)

**Comment by BreadGenie** [comment]
Click on "upload" button to the upload the selected file.
After that you can click on "x attachments" beside the upload attachment button to copy link for the file.

**Comment by parameshnalla** [comment]
Hi @BreadGenie thank you for the response. I did upload the files, and after uploading it showed as 1 attachment, but as you as submit the changes, the attachment is no longer visible on the wiki page

**Comment by hasnain2808** [comment]
@parameshnalla 
The use case of the attachments tool at the moment is to get the URL of the file that was uploaded so that it can be used further in the edit of the Wiki
It does not list all the attachments to the document 
This may or may not be useful and can be discussed

**Comment by BreadGenie** [comment]
Markdown editor is now removed from #124 (you can still write markdown on the new editor) and file uploader isn't used anymore.
