### ISSUE TITLE
Wiki page upload attachment button in edit page not working

### ISSUE THREAD

**Issue by honey-sharma1012** [frappe/wiki#126]
When  i am clicking on upload attachment button , in edit page , the popup for upload attachment is showing an empty dialog box with only upload button ### 

![Wiki issue ](https://user-images.githubusercontent.com/127949330/225524960-ee4ec8aa-7c2a-4cce-9f0e-30428c9ce447.png)

**Comment by honey-sharma1012** [comment]
This is deployed over Frappe cloud with the versions below,

Frappe Framework: v14.27.0 (HEAD)
Wiki: v0.0.1 (HEAD)

URL - wiki.nestorbird.com

**Comment by ashishsaretia** [comment]
I have updated and this didn't work for me. Please find the clip here,

[DRIP.webm](https://user-images.githubusercontent.com/10839039/227009013-1a449393-1964-4446-8b1d-1fbc6a914ca4.webm)

**Comment by BreadGenie** [comment]
Can you try going to File List from desk and click on Add File and see if the file uploader is loaded properly?

**Comment by ashishsaretia** [comment]
Yes, in File List the uploader is working fine but not working on document edit screen as shown in my previous message here.

**Comment by honey-sharma1012** [comment]
![Screenshot from 2023-03-23 15-35-42](https://user-images.githubusercontent.com/127949330/227170867-71b081ea-5e35-4be2-ba3c-af6eb1419599.png)
![Screenshot from 2023-03-23 15-36-39](https://user-images.githubusercontent.com/127949330/227170906-c3275afa-cc7d-47e4-a132-7bb3d6247f16.png)


I have attached the image , please check in Preview

**Comment by OneiricIT** [comment]
This is also now occurring for us too with recent update. e.__ is not a function when selecting upload attachment when editing a wiki page.

**Comment by BreadGenie** [comment]
This issue will be resolved in #124

**Comment by BreadGenie** [comment]
Closing this, since it's not relavant from #124
