### ISSUE TITLE
edit timestamp is wrong

### ISSUE THREAD

**Issue by saru2020** [frappe/wiki#130]
hi,

how do I modify the timestamp of the page edit?
it always shows/takes the timestamp the page was created and not when it was edited

for example, I just edited a page but it still shows 5months ago when it was created
<img width="542" alt="Screenshot 2023-04-01 at 3 18 55 AM" src="https://user-images.githubusercontent.com/1034916/229239109-8c92495b-82e2-47ff-bac4-e71541cfeae2.png">

is there a way to show the last edited timestamp?

I tried editing the page, unpublishing & republishing the page but nothing seems to work

**Comment by BreadGenie** [comment]
Are you on the latest commit?

It works for me on the latest commit with Frappe v14 and develop.
![image](https://user-images.githubusercontent.com/63963181/229263963-7d82ec74-f59c-4394-ad5e-2f33c8a975e8.png)
![image](https://user-images.githubusercontent.com/63963181/229263974-25a247b2-404c-4e8e-a591-4149718538fa.png)

(a minute passed in between the screenshots 😄)

**Comment by BreadGenie** [comment]
Closing since this isn't relevant after #124

**Comment by saru2020** [comment]
with the latest/master changes/branch, I'm still seeing this issue:

though I've edited this Wiki page, I'm still seeing not seeing the timestamp updated: 
<img width="472" alt="Screenshot 2023-04-09 at 12 08 57 AM" src="https://user-images.githubusercontent.com/1034916/230737611-89cd0224-3090-4e65-ba6e-8ebe4c571399.png">
