### ISSUE TITLE
Wiki page not render properly

### ISSUE THREAD

**Issue by JRII972** [frappe/wiki#137]
I've install the wiki app on a fresh new bench instance (without erpnext install). And when i go to the home page, that what i got.

I trie to add a new wiki page, and it notadd a new sidebar link, and nothing change.

![image](https://user-images.githubusercontent.com/59899019/230954782-bd181537-593d-4d64-ac8c-f097b641ffca.png)

![image](https://user-images.githubusercontent.com/59899019/230955886-b7ce673c-aad0-4d4a-bf37-b326ccd5531a.png)

I follow all step, and after I tried again by installing the missing NPM dependencies

What is my mistake !

Thx by advance.

**Comment by BreadGenie** [comment]
I need more context (wiki version, frappe version etc) to help you out. 
Can you also try going to /app and see if you've done the initial setup (selecting languages, nation, currency etc)? I've seen sometimes pages being deformed when setup isn't done

**Comment by BreadGenie** [comment]
> Oh sorry I forget to add that.
> Wiki 0.0.1 last version form GitHub (today) 
> Frappe 14.29

I believe there's a latest Frappe version maybe update to it.

> I new in bench. So do I have to restart from a new site ? (Now it's not a problem if that solve the issue)

I'm not sure if creating a new site is going to help

> (Also I run it inside Docker, I don't know if that change anything)

Maybe install bench the other way and see if it works? (theoretically it shouldn't change anything)

**Comment by JRII972** [comment]
I started over from scratch and everything worked fine. I'm still on docker, but this time I installed wiki before the first launch of the site.

Thank you all the same for the help, but for this great job you have done.
