### ISSUE TITLE
No way to resize tables and their columns in Wiki

### ISSUE THREAD

**Issue by pushkarjsh88** [frappe/wiki#146]
There should be a way for the user to resize tables created on Wiki pages. Currently, there is no way to get the tables resized as per the respective content. As a result, few columns get displayed broader than the actual required width.

Also, the tables created in Wiki pages can't be made smaller if required. Hence, a lot of space is consumed by the tables than they actually require.

![image](https://user-images.githubusercontent.com/89507981/234827915-a6b2aeef-80db-4391-8ea2-21ba352c604c.png)

**Comment by nilpatel42** [comment]
My code is already updated but after resizing the column when i save wiki page, its not changing
