### ISSUE TITLE
wiki page , private issue

### ISSUE THREAD

**Issue by Ragevn** [frappe/wiki#163]
whenever i logged in or not i can read the page without problems, only when try to edit then the site request log in, even though i uncheck "allow guest" option in wiki page
![image](https://github.com/frappe/wiki/assets/118674380/50fc277d-c985-4e0f-9b63-aadd21619bc2)

![image](https://github.com/frappe/wiki/assets/118674380/be6f482b-97b3-4866-8e61-cb791a07d905)

my frappe version : 
chat 0.0.1 main (2b04b14)
erpnext 14.27.7 version-14 (58e304f)
frappe 14.39.0 version-14 (ca8701c)
hrms 14.4.3 version-14 (637691b)
lms 1.0.0 main (d19538a)
wiki 2.0.0 version-14 (c2f0a40)

**Comment by BreadGenie** [comment]
The allow uncheck option is only for read permission, not edit permission. Letting guests have edit permission can be disastrous.
