### ISSUE TITLE
Every time i need to change column width & cell merge option is not available

### ISSUE THREAD

**Issue by nilpatel42** [frappe/wiki#165]
when i edit wiki page second time it will reset to it's real width, every time i need to change column width
also have cell merge option not available which is the most need function for table  

_Originally posted by @nilpatel42 in https://github.com/frappe/wiki/issues/164#issuecomment-1615530692_

**Comment by BreadGenie** [comment]
cell merge option is added in cec650064768ee488ea6e2d99ba1e1eecc129090. I've reopened the other issue for tracking the width bug.
