### ISSUE TITLE
search bar not properly working

### ISSUE THREAD

**Issue by nilpatel42** [frappe/wiki#167]
>  please give me the update code for search bar properly working (my search bar appear left side of the page - i think it have be center of the page)

You can make changes to the searchbar by adding css through website theme

_Originally posted by @BreadGenie in https://github.com/frappe/wiki/issues/166#issuecomment-1616664566_
 
I have main issue is that search bar not give result from my wiki it always show the no results

**Comment by BreadGenie** [comment]
If you don't have redisearch properly configured then you can use frappe web search.
Go to Wiki Settings -> Navbar  and then untick `use redisearch`

**Comment by nilpatel42** [comment]
My ERPNext Version is V14

**Comment by BreadGenie** [comment]
are you on master branch or version-14 branch?

**Comment by nilpatel42** [comment]
version-14

**Comment by BreadGenie** [comment]
I've updated the version-14 branch can you try it again?

**Comment by nilpatel42** [comment]
working thanks
