### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by nilpatel42** [frappe/wiki#168]
Suggestion for improving wiki

1. Underline For Text
2. Font size variable (Important update) 
3. Font Color
4. Cell Color 
5. Links Button (Frappe Docs Currently Using)
6. YouTube or Other Video embed Button like link URL
7. Page with password protection feature (Media wiki have)
8. Collapsible sidebar (Left sided)
9. Small logo in wiki page title and group title like ERPNext have
10. Zoom out and Zoom in automatically according to content because when table width is higher than regular it will shrink the table, content not showing properly   
11. BUG - In some pages when click on page, after loading page it will automatically scroll to the content anywhere (title will going under header of website)
12. When we merge 3, 5, 7, etc cell in column, text not be in vertically center

**Comment by the3dfox** [comment]
push, especially the essential text editor functions
