### ISSUE TITLE
Wiki not loading for user without System Admin and Wiki Approval role

### ISSUE THREAD

**Issue by nilpatel42** [frappe/wiki#172]
**When i add Wiki Approval Permission but i tick "if created by" then it not working, it show many redirect error**
Wiki version : v2.0.0 (version-14)
ERPNext : v14.27.12 (version-14)
Frappe Framework : v14.40.0 (version-14)

In Firefox
![image](https://github.com/frappe/wiki/assets/135511086/86636386-4181-4c2d-9e61-91d9418f050d)

and i also add code in terminal 
```
/frappe-bench/apps/frappe/frappe/utils/caching.py:57: DeprecationWarning: `frappe_last` argument is deprecated and will be removed in v15.
17:52:45 web.1            |   return_val = func(*args, **kwargs)
17:52:45 web.1            | 192.168.1.210 - - [17/Jul/2023 17:52:45] "GET /login?redirect-to=http%3A%2F%2F192.168.1.147%3A8000%2Fwiki%2Fabout-abc HTTP/1.1" 301 -
17:52:45 web.1            | 192.168.1.210 - - [17/Jul/2023 17:52:45] "GET /wiki/about-abc HTTP/1.1" 301 -
17:52:45 web.1            | /home/abc/frappe-bench/apps/frappe/frappe/utils/caching.py:57: DeprecationWarning: `frappe_last` argument is deprecated and will be removed in v15.
17:52:45 web.1            |   return_val = func(*args, **kwargs)
17:52:45 web.1            | 192.168.1.210 - - [17/Jul/2023 17:52:45] "GET /login?redirect-to=http%3A%2F%2F192.168.1.147%3A8000%2Fwiki%2Fabout-abc HTTP/1.1" 301 -
17:52:45 web.1            | 192.168.1.210 - - [17/Jul/2023 17:52:45] "GET /wiki/about-abc HTTP/1.1" 301 -
17:52:45 web.1            | /home/abc/frappe-bench/apps/frappe/frappe/utils/caching.py:57: DeprecationWarning: `frappe_last` argument is deprecated and will be removed in v15.
17:52:45 web.1            |   return_val = func(*args, **kwargs)
17:52:45 web.1            | /home/abc/frappe-bench/apps/frappe/frappe/utils/caching.py:57: DeprecationWarning: `frappe_last` argument is deprecated and will be removed in v15.
17:52:45 web.1            |   return_val = func(*args, **kwargs)
17:52:45 web.1            | 192.168.1.210 - - [17/Jul/2023 17:52:45] "GET /login?redirect-to=http%3A%2F%2F192.168.1.147%3A8000%2Fwiki%2Fabout-abc HTTP/1.1" 301 -
17:52:45 web.1            | 192.168.1.210 - - [17/Jul/2023 17:52:45] "GET /website_script.js HTTP/1.1" 200 -
17:52:45 web.1            | 192.168.1.210 - - [17/Jul/2023 17:52:45] "GET /wiki/about-abc HTTP/1.1" 301 -
17:52:45 web.1            | /home/abc/frappe-bench/apps/frappe/frappe/utils/caching.py:57: DeprecationWarning: `frappe_last` argument is deprecated and will be removed in v15.
17:52:45 web.1            |   return_val = func(*args, **kwargs)
17:52:45 web.1            | 192.168.1.210 - - [17/Jul/2023 17:52:45] "GET /login?redirect-to=http%3A%2F%2F192.168.1.147%3A8000%2Fwiki%2Fabout-abc HTTP/1.1" 301 -
17:52:45 web.1            | 192.168.1.210 - - [17/Jul/2023 17:52:45] "GET /wiki/about-abc HTTP/1.1" 301 -
17:52:46 web.1            | /home/abc/frappe-bench/apps/frappe/frappe/utils/caching.py:57: DeprecationWarning: `frappe_last` argument is deprecated and will be removed in v15.
17:52:46 web.1            |   return_val = func(*args, **kwargs)
17:52:46 web.1            | 192.168.1.210 - - [17/Jul/2023 17:52:46] "GET /login?redirect-to=http%3A%2F%2F192.168.1.147%3A8000%2Fwiki%2Fabout-abc HTTP/1.1" 301 -
17:52:46 web.1            | 192.168.1.210 - - [17/Jul/2023 17:52:46] "GET /wiki/about-abc HTTP/1.1" 301 -
```
This code run repetitively when i refresh or trying to get wiki page

**Comment by nilpatel42** [comment]
> Sorry I didn't get what you meant by "if created by" in the description. Can you elaborate a bit more on that?

sorry
its If only Creator

**Comment by nilpatel42** [comment]
> Sorry but where is the "it's if only creator" field at?

in role permission manager

**Comment by BreadGenie** [comment]
What doctype did you change it?
I enabled the "Only if Creator" from role perm manager to all wiki doctypes and it works fine for me (opened it on private mode)

**Comment by nilpatel42** [comment]
> In what doctype did you change it?
> I enabled the "Only if Creator" from role perm manager to all wiki doctypes and it works fine for me (opened it as guest too)

- first problem is without given user to wiki aproover role or admin , wiki not working (my all wiki page is disabled for guest)
- When i enable the checkbox in wiki page doctype, its not working
- but when it disable and wiki aproover role given to user its working

**Comment by BreadGenie** [comment]
Are you trying to make it so that the creators of the page only can view the wiki page?

If yes that's not the purpose of Wiki. It's supposed to host content/documentation that's supposed to be shared among others (public or within your team (read no guests allowed))

**Comment by nilpatel42** [comment]
okay i understand 
i want share docs within my team 
but why user not access wiki when wiki approver or admin role not assign 
if i am correct without that both role wiki must accessible to users who have login credentials to ERPNext

Thank you

**Comment by BreadGenie** [comment]
> if i am correct without that both role wiki must accessible to users who have login credentials to ERPNext

You're right the pages can be made inaccessible to only guests atm.

There's an ongoing issue #60 that tracks the feature that you want.
