### ISSUE TITLE
Darkmode not supported properly

### ISSUE THREAD

**Issue by cdiethelm** [frappe/wiki#181]
Hi, 

I scrolled through the frappe wiki pages and saw that the darkmode doesnt seem to work correctly on links and menu items.

![image](https://github.com/frappe/wiki/assets/46853231/c6cc4a2c-0cdc-4b4f-b501-cafd126b0a07)

Also the sandwich menu is black, so the user cant see that.
![image](https://github.com/frappe/wiki/assets/46853231/45f3042e-2f0a-4f8e-bf04-f8caea336558)

Active menu items are hidden. 
![image](https://github.com/frappe/wiki/assets/46853231/90d05e8e-5032-4689-abb6-59832680d3a2)

Also, these outlines are hidden when on darkmode, the titles are black so they also cant be seen: 
![image](https://github.com/frappe/wiki/assets/46853231/3343b798-49aa-4681-b10b-e673b095b976)
![image](https://github.com/frappe/wiki/assets/46853231/a8021772-61ee-4f0d-8adc-e3eee8864201)

**Comment by BreadGenie** [comment]
Thanks for bringing this to attention. This happened due to the primary color changes in frappe desk following the new espresso design. I'll fix it shortly.
