### ISSUE TITLE
Sidebar menu links are wrongly formed

### ISSUE THREAD

**Issue by atn-prabhu** [frappe/wiki#190]
The sidebar menus are directing to wrong URL. eg. _https://erpdev.mydomain.com/desk#Form/Website%20Sidebar/Wiki%20Sidebar_
Notice the **#** between **desk** and **Form**. Same works fine when replaced with a **/** (slash)

The right URL is _https://erpdev.mydomain.com/desk/Form/Website%20Sidebar/Wiki%20Sidebar_

**Comment by BreadGenie** [comment]
I can't really pinpoint the issue here. Is the issue in the sidebar of Wiki? What version of Wiki and Frappe are you using? Screenshots?

**Comment by atn-prabhu** [comment]
Ubuntu 22.04.3 LTS
frappe 14.51.0
erpnext 14.43.0
wiki 0.0.1

In the **Wiki Sidebar**  (https://erpdev.mydomain.com/desk/Form/Website%20Sidebar/Wiki%20Sidebar) noticed that the existing two links 

> Edit Sidebar
> Settings

are having the Route with # instead of /.

Rectifying the same by navigating to 

> Website > Website Sidebar > Wiki Sidebar 

fixed the issue.

**Comment by BreadGenie** [comment]
It looks like you're using an older version of Wiki. Please update it and make sure you're using `version-14` branch.
