### ISSUE TITLE
‘Allow Guest’ feature not working

### ISSUE THREAD

**Issue by jpettan** [frappe/wiki#200]
Have created wiki pages with ‘Allow Guest’ not checked.

These wiki pages are still accessible. Is there something further that needs to be done to get this feature activated?

I am using frappecloud with frappe version 14 and latest update of wiki as per frappe cloud.

**Comment by BreadGenie** [comment]
Are you using version-14 branch of Wiki in Frappe Cloud?

**Comment by garamizo** [comment]
I am also having this issue using Frappe cloud version-15, Wiki master branch.
