### ISSUE TITLE
On each wiki space, 1st wiki Menu has to be English, other language, i.e., Thai will throw error.

### ISSUE THREAD

**Issue by kittiu** [frappe/wiki#214]
As I create Wiki Space = payroll-guide

If I got to /payroll-guide, this will work as the first menu is English

![image](https://github.com/frappe/wiki/assets/1973598/d8067d7c-1ecc-4704-99a5-2e27a93dd5a5)

But if I move the Thai menu up and go to /payroll-guide again, this will not work.

![image](https://github.com/frappe/wiki/assets/1973598/99841785-9bc0-4947-95e0-75f16048d158)

**Comment by BreadGenie** [comment]
I was not able to debug the issue here

https://github.com/frappe/wiki/assets/63963181/af736a42-4fdc-466f-b379-0b6c3de4ce0a

I'm guessing it might have something to do with the `cleanup_page_name` function.

Can you specify the version details of your apps using `bench list-apps`?
