### ISSUE TITLE
How to make purple text

### ISSUE THREAD

**Issue by federicocalvo** [frappe/wiki#223]
**Descripction:**

a silly question, which I did not find how to answer in the documentation or on my own.

How do I make this purple code text?

![Captura de pantalla 2024-03-31 a la(s) 12 27 26](https://github.com/frappe/wiki/assets/7256766/24202df1-baa9-4635-bfbc-d3a6fffad7b0)

**Comment by BreadGenie** [comment]
you can use backtick (`) for that
just wrap the word between 2 backticks

**Comment by federicocalvo** [comment]
@BreadGenie Thanks for response, but dont work. I have a version 2.0

**Comment by BreadGenie** [comment]
That's weird. Can you give me more info regarding what browser, wiki branch and all so I could take a look?

https://github.com/frappe/wiki/assets/63963181/1d034f2a-5b43-4778-aab1-c8ae5d1b0646

Here's me doing creating it with backticks
