### ISSUE TITLE
version 15

### ISSUE THREAD

**Issue by wojosc** [frappe/wiki#242]
Is there no Version 15 branch for this? How come you guys are not following the usual frappe structure of branches

develop
version-14
version-15

etc

**Comment by BreadGenie** [comment]
You can treat the master branch as version 15 branch. Nothing other than fixes go in there on that branch at the moment. 

> How come you guys are not following the usual frappe structure of branches

No other apps than ERPNext follows that structure afaik. Take a look at [insights](Ihttps://github.com/frappe/insights), [gameplan](https://github.com/frappe/gameplan) or [helpdesk](https://github.com/frappe/helpdesk/)
