### ISSUE TITLE
Wiki UX fixes

### ISSUE THREAD

**Issue by rmehta** [frappe/wiki#249]
- [x] Home page for docs.frappe.io
- [x] Clear cache when wiki space navbar is updated
- [x] Remove scrolling animation for sidebar
- [x] Remove dark mode switch ([use auto](https://stackoverflow.com/questions/50840168/how-to-detect-if-the-os-is-in-dark-mode-in-browsers)]
- [x] Page edit options near title (?)
- [x] 15px for body font? https://frappecloud.com/draft/home

**Comment by pranjal-tank** [comment]
hello @rmehta I have already raised PR against point 3, can you please review it.

[https://github.com/frappe/wiki/pull/248](url)
