### ISSUE TITLE
Toolbar for text formatting

### ISSUE THREAD

**Issue by aidemkin** [frappe/wiki#277]
After updating to version 2.0.1, the content editor no longer displays the toolbar for text formatting. How can I configure or restore the toolbar that was previously available?

<img width="1309" alt="img" src="https://github.com/user-attachments/assets/0f898f9a-d04d-43fa-8c1e-442d206a90c4">

**Comment by AyshaHakeem** [comment]
@aidemkin , The editor is now in markdown. If you'd like to undo these changes, consider reverting your Wiki instance to a previous commit and restoring a backup from before the migration.

**Comment by aidemkin** [comment]
Thank you for the quick response! Please consider implementing a user-friendly Markdown editor for business users who can use it without IT experience. The current solution is convenient only for technically experienced specialists. My proposal would allow maintaining the technical approach of using Markdown but with a more user-friendly and intuitive interface for any user.
