### ISSUE TITLE
Why was WYSIWYG Editor removed?

### ISSUE THREAD

**Issue by revant** [frappe/wiki#279]
I can understand it is complex to maintain editor and related code logic.
It was easy for non developer users to add posts to wiki. Copy content from ms word and paste in editor maintained format.

If it can be reverted it'll be great!

edit: For who wish to not upgrade because of editor, use this fork and branch https://github.com/castlecraft/wiki/tree/wysiwyg-editor

**Comment by revant** [comment]
Business users I interact with (large number of them) are going to stay with WYSIWYG.

The immediate reaction is we're not going to upgrade anyway!

Follow this for better https://github.com/frappe/wiki/issues/281

**Comment by c-l-v** [comment]
Why was it removed?  I've recently realised the editor has disappeared and can't find any explanation as to why?  

As a non-developer end user, this seems like a bizarre decision.  As a relative newcomer to ERPNext / Frappe, is this how things work?  Do features that are valuable to end users suddenly get cut out for no apparent reason?
