### ISSUE TITLE
Show permalinks only on focus

### ISSUE THREAD

**Issue by hasnain2808** [frappe/wiki#28]
Permalinks show up for all heading and are persistent
![image](https://user-images.githubusercontent.com/28212972/131340239-97f139fc-022b-41d0-a4b9-000bcb3e2e59.png)
A better idea is to keep them on the left(of the heading) and show only on hover
![Kapture 2021-09-03 at 11 50 23](https://user-images.githubusercontent.com/28212972/131959603-2633db59-39f4-4707-b1e2-79becc201d7f.gif)

**Comment by BreadGenie** [comment]
Fixed by 52ab9268ef5cbf6ef5f91c8ee6cf66fa1ab59105
I've yet to chose to move it to the left since that requires either changes in framework or replacing the link icon and then adding it back on the left
