### ISSUE TITLE
Data Mismatch After Saving and Viewing a New Document

### ISSUE THREAD

**Issue by AbleKSaju** [frappe/wiki#298]
https://github.com/user-attachments/assets/e6f17962-abff-4876-9cca-f9df5fb87b2f

Description:

The data appears correctly in the preview before creating and saving a new document. However, when opening the document for further review after saving, the data is incorrect or inconsistent.

Steps to Reproduce:

Create a new document.
Save the document.
Open the contributions.

Expected Behavior:
The data should remain consistent between the preview and the detailed view.

Observed Behavior:
The data in the document appears to be incorrect upon opening.

**Comment by rmehta** [comment]
@AyshaHakeem can you check?

**Comment by AyshaHakeem** [comment]
Fixed via: #306
