### ISSUE TITLE
Implement Collaborative Text Editor

### ISSUE THREAD

**Issue by matbrgz** [frappe/wiki#34]
Hello,

Collaborative editing is the editing of groups producing works together through individual contributions. Effective choices in group awareness, participation, and coordination are critical to successful collaborative writing outcomes.

![image](https://user-images.githubusercontent.com/23284276/135103817-277dd2ed-4875-42c8-b230-028bd301374e.png)

I suggest the implement [TipTap](https://tiptap.dev/)

**Comment by hasnain2808** [comment]
@matbrgz 
I believe this will be a nice addition.
Feel free to raise a PR

**Comment by cgallay** [comment]
This feature would be awesome to have!

**Comment by rmehta** [comment]
Maybe after we get 10000 stars

**Comment by matbrgz** [comment]
> @matbrgz I believe this will be a nice addition. Feel free to raise a PR

Any suggestion how to start this implementation? Could you guide me?
