### ISSUE TITLE
Implement 3rd Party Embed

### ISSUE THREAD

**Issue by matbrgz** [frappe/wiki#35]
Embed means to integrate external content into another website or page. You embed something when you place a block of code — called an embed code — into the HTML editor of another website.

**The problem I am facing**
I’m always frustrated when creating documents that need to show documents that isn't possible to bring to FrappeWiki.

**The solution I would like**
Embed means to integrate external content into another website or page. You embed something when you place a block of code — called an embed code — into the HTML editor of another website.

![image](https://user-images.githubusercontent.com/23284276/135104216-7f8f807a-a3e8-42a7-9275-af463a44241b.png)

**Suggestion to Embed**
- [ ] [Google Knowledge Graph Search API](https://en.wikipedia.org/wiki/Knowledge_Graph)
- [ ] Abstract
- [ ] Adobe Dimension
- [ ] Adobe Spark 
- [ ] Adobe XD
- [ ] AirTable
- [ ] Any URL
- [ ] ArcGIS StoryMap
- [ ] Asana
- [ ] BambooHR
- [ ] Behance
- [ ] ClickUp (https://docs.clickup.com/en/articles/3714856-public-sharing)
- [ ] CodePen
- [ ] DailyMotion
- [ ] Descript
- [ ] Diagrams.Net
- [ ] embed.ly
- [ ] Facebook Post
- [ ] Figma
- [ ] Flickr
- [ ] Framer
- [ ] Giphy
- [ ] GitHub Gist
- [ ] Google 
- [ ] Google Analytics
- [ ] Google Calendar
- [ ] Google Colaboratory
- [ ] Google Docs
- [ ] Google Maps
- [ ] Google Slides
- [ ] Google Spreedsheet
- [ ] iframely
- [ ] Instagram HashTag Feed
- [ ] Instagram Post
- [ ] Instagram Profile Feed
- [ ] Instagram Profile Grid
- [ ] InVision
- [ ] ion interactive
- [ ] jsFiddle
- [ ] Kickstarter Campaign
- [ ] Kickstater Catalogue
- [ ] Leanboard
- [ ] LinkedIn Post
- [ ] Linkedin SlideShare
- [ ] Looker
- [ ] Lucidchart
- [ ] Marvel
- [ ] Metabase (https://www.metabase.com/docs/latest/administration-guide/13-embedding.html)
- [ ] Microsoft PowerBI
- [ ] Mindmeister
- [ ] Miro
- [ ] Notion
- [ ] Overflow.io
- [ ] Pastebin.com
- [ ] Plunker
- [ ] Prezi
- [ ] RunKit
- [ ] Scribd
- [ ] Snipit
- [ ] Speakerdeck
- [ ] Spotify Playlist
- [ ] StackShare
- [ ] Taiga
- [ ] TED
- [ ] TikTok
- [ ] Tiled
- [ ] Trello
- [ ] Trello Board
- [ ] Trello Card
- [ ] Tumblr
- [ ] TuneUp
- [ ] Twitter HashTag Timeline
- [ ] Twitter Profile Feed
- [ ] Twitter Tweet
- [ ] TypeForm
- [ ] Visual.ly
- [ ] Whimsical or Mermaid
- [ ] Wikimedia
- [ ] Wikipedia
- [ ] WordPress Blog Post
- [ ] Wordpress Blog Post Catalogue
- [ ] Yelp
- [ ] YouTube

**Comment by rmehta** [comment]
Should be fixed with #237

**Comment by matbrgz** [comment]
@rmehta Markdown may not solve this, some embed requires more than HTML embed. IMO, [Iframely](https://iframely.com/) should solve this with an elegant solution.
