### ISSUE TITLE
existing wiki paged cannot be added from the edition

### ISSUE THREAD

**Issue by federicocalvo** [frappe/wiki#43]
## Description of the issue
When you want to add wiki page to the sidebars, you can't call it from the selector

https://user-images.githubusercontent.com/7256766/139920784-1d2796ff-b0fe-462a-ac6e-9ce3af9a5542.mov

## Context information (for bug reports)
Editing any wiki page to be able to edit the siderbar

**Output of `bench version`**
```
Frappe Version 13.11
ERPNext Version 13.11
Wiki Version 1.0.0 branch version-13
```

**Comment by BreadGenie** [comment]
Closing this issue since we have removed adding pages via Sidebar from 5448346c35f13b51fad4de0b1cd9b2fdac465842
