### ISSUE TITLE
wiki pages indexed in the search engine

### ISSUE THREAD

**Issue by federicocalvo** [frappe/wiki#44]
## Description of the issue
I believe this is not an issue, but a query that I did not find an answer to.

Are there any settings that I am not taking into account to get the wiki pages indexed in the search engine?

Ej. docs ERPnext oficial:
![Captura de Pantalla 2021-11-02 a la(s) 15 42 29](https://user-images.githubusercontent.com/7256766/139926534-d519085b-e118-47d3-a03e-51a652a9228a.png)

Thanks for advance.

**Output of `bench version`**
```
Frappe Version 13.11
ERPNext Version 13.11
Wiki Version 1.0.0 branch version-13
```

**Comment by hasnain2808** [comment]
Go to Website Settings and turn on `include search in top bar`

![image](https://user-images.githubusercontent.com/28212972/140764747-2a4b0a93-f78c-4667-a477-0367c17c22cf.png)
