### ISSUE TITLE
Show edit button on top of the page

### ISSUE THREAD

**Issue by ChillarAnand** [frappe/wiki#48]
For the new users, it is not evident that the site(for example https://docs.erpnext.com) is not built on top of wiki until they reach the bottom of the page.

If we show `Edit Page` button on top or somewhere where it is visible without scrolling, it will help new users.

**Comment by BreadGenie** [comment]
I have noticed that the edit page button/option is placed at the bottom on more prominent alternatives like VitePress, Docusaurus, Gatsby etc. So users might find the edit on bottom more intuitive (if they have prior experience with the above mentioned options). I'll leave this issue open till we have more opinion on the topic.

**Comment by BreadGenie** [comment]
added in #124
