### ISSUE TITLE
Search bar exclusively in wiki

### ISSUE THREAD

**Issue by federicocalvo** [frappe/wiki#49]
**Is your feature request related to a problem? Please describe.**
The ERPNext wiki is in a separate instance of the ERPNext website.

But the idea of being an app is that one can use it as one more of all the apps out there.

If for example ERPNext.com would have the wiki search engine currently activated, you would see it in your navbar on the web, and it does not look good and is not useful.

**Describe the solution you'd like**

So the search engine in the wiki, should have the possibility to be configured in the Setting, so that it only appears in the wiki page.
**Describe alternatives you've considered**
Actualy we have that script:
```
if (window.location.pathname.indexOf("doc") != 1) {
	$('form[action="/search"]').hide();
}
```

But its not ideal 😅

**Additional context**

**Comment by karrykreates** [comment]
Will you be adding this to the version-13 branch?
