### ISSUE TITLE
TypeError: preview() missing 2 required positional arguments: 'content' and 'name'

### ISSUE THREAD

**Issue by sliwkawsieci** [frappe/wiki#50]
I am getting that error "TypeError: preview() missing 2 required positional arguments: 'content' and 'name'" on frapecloud in wikipage xxx.frappe.cloud/app/wiki-page-patch/new-wiki-page-patch-1

the same is on my local server but sometimes in some other places. It may be somehow connected with update v13.14 ?
![image](https://user-images.githubusercontent.com/19532577/143019954-7ab19763-947a-467f-97e3-e658a1fe6bba.png)

**Comment by ankush** [comment]
can you share traceback from browser's console?

**Comment by sliwkawsieci** [comment]
> can you share traceback from browser's console?

sure 
![image](https://user-images.githubusercontent.com/19532577/143446169-28152e8d-a5be-4b04-b432-0f6ccec0fd4f.png)

**Comment by techseria** [comment]
Same error i am also getting in erpnext v13

**Comment by asemoq** [comment]
I have almost the same error TypeError: preview() missing 1 required positional argument: 'content' and TypeError: object of type 'NoneType' has no len() 
App Versions
"erpnext": "14.13.0",
"frappe": "14.23.0",
"wiki": "0.0.1"

**Comment by BreadGenie** [comment]
@asemoq can you explain a bit more about what you were trying to do?

**Comment by asemoq** [comment]
> @asemoq can you explain a bit more about what you were trying to do?

I tried to open wiki page patcher
