### ISSUE TITLE
Wiki Sidebar not found

### ISSUE THREAD

**Issue by blewsky** [frappe/wiki#51]
I installed the Wiki app on Frappe Cloud. The sidebar seems to be broken:
![image](https://user-images.githubusercontent.com/87971956/143963713-c4dd8b1c-8879-4946-a618-e867598b98a9.png)

If I enter in ERPnext, I also get the same error message:
Step 1:
![image](https://user-images.githubusercontent.com/87971956/143963788-f2060ca8-2f0d-419e-b9f0-7aac75487db0.png)
Step 2:
![image](https://user-images.githubusercontent.com/87971956/143963678-1bb63b4b-4d8a-407d-9a6c-625f74ed6fc5.png)

ERPNext: v13.14.1 (version-13)
Frappe Framework: v13.14.1 (HEAD)
Wiki: v0.0.1 (HEAD)

**Comment by hasnain2808** [comment]
@blewsky 
Click on the Wiki Sidebar option. The link field will suggest an existing sidebar. Please select one of those sidebars
