### ISSUE TITLE
"No results found" Search not working - branch version-13

### ISSUE THREAD

**Issue by ghost** [frappe/wiki#57]
Frappe Framework: v13.15.0 (version-13)

Wiki: v0.0.1 (version-13)

**Comment by hasnain2808** [comment]
@karrykreates 
Until this is fixed the workaround is this
The search takes the scope as the name of the top level sidebar
Go to wiki sidebar list and set the root sidebar's name name to the base path of your wiki pages in which you want to search

**Comment by PatelN123** [comment]
@hasnain2808 @BreadGenie 
How do we set a path?

**Comment by BreadGenie** [comment]
@PatelN123 in the wiki settings the `Wiki Sidebar` field will autocomplete for a list of Wiki Sidebars. Pick or type the one that's the root wiki sidebar. By default the root sidebar is "wiki".

**Comment by PatelN123** [comment]
@BreadGenie Yes, this changes the sidebar correct?
I mean how exactly can I get the search working?

**Comment by BreadGenie** [comment]
No, it doesn't change the sidebars. The searchbar is looking for a scope for search to work. And the workaround here is adding the root sidebar for the search's scope.

**Comment by PatelN123** [comment]
@BreadGenie Okay, so I have tried to set the sidebar to `wiki` and some others that I have made. Each of them still result in the search not working. Please advise what the next fix is.

> root sidebar's name name to the base path of your wiki pages

I see this but I can see no documentation on how to set the base path.
I assume the base path means something like setting this? (/docs/)
![image](https://user-images.githubusercontent.com/79650289/226715938-3e43dcbf-3a50-4388-a216-561181c14bb8.png)

Please advise.

**Comment by BreadGenie** [comment]
Yes, briefly you'll have to do 3 things to get this working
- add the base path to every wiki page to get them indexed. So all wiki pages will be appended by a base path like /docs/
- root sidebar should be renamed as to the base path (here it's "docs")
- Set the base path to `Wiki Sidebar` field in Wiki Settings

**Comment by PatelN123** [comment]
Thank you for clarifying @BreadGenie.
How can us users have it auto set the base path like /docs/? - I am sure others will agree when I say it is a pain to go to each docs page and change it when we make a new page.

**Comment by BreadGenie** [comment]
I agree. Currently we don't have a way out of the box at the moment, but it will be coming very soon to wiki.

**Comment by BreadGenie** [comment]
resolved in #124

**Comment by yasser1248** [comment]
I have same problem and still not solved 
any help please
