### ISSUE TITLE
is there support for RTL view for languages like Hebrew and Arabic?

### ISSUE THREAD

**Issue by aymenit2008** [frappe/wiki#65]
I have documenteds by Arabic language . I want to change the view from ltr to rtl

**Comment by hadeeld7** [comment]
question, did you add the Arabic content in the pages ? like you plan to use this only for Arabic ?

**Comment by hadeeld7** [comment]
use ` <html dir="rtl"> ` for your content that should fix it 👍

**Comment by BreadGenie** [comment]
You can press on right align button in the editor to type them from right to left
