### ISSUE TITLE
Installation Error - got an unexpected keyword argument 'pluck'

### ISSUE THREAD

**Issue by techseria** [frappe/wiki#66]
We are getting error while installing wiki app in erpnext version 13

Installing wiki...
Updating DocTypes for wiki          : [========================================] 100%
An error occurred while installing wiki:
get_values() got an unexpected keyword argument 'pluck'

**Comment by singhranbir** [comment]
I am also facing the same issue

**Comment by Abdo2021-a** [comment]
me too face this issue but its work

**Comment by GoldenScrew** [comment]
the same!!!

**Comment by ankush** [comment]
https://github.com/frappe/wiki/blob/82c4b64aa6582a4abc52fe38766bf5e4b428db07/wiki/wiki/doctype/wiki_sidebar/wiki_sidebar.py#L14 

This should be changed to `get_all`. @hasnain2808

**Comment by GoldenScrew** [comment]
@hasnain2808 when it will be fix? I can't use wiki...

**Comment by hasnain2808** [comment]
@techseria @GoldenScrew @singhranbir @Abdo2021-a 
What is the branch/ release of wiki that you are trying to install?

The master branch of wiki supports only the develop branch of Frappe/ ERPNext
The version-13 branch was created to address this problem but is not updated with the latest features/ fixes since frappe's develop branch has diverged a lot from v13

**Comment by GoldenScrew** [comment]
> @techseria @GoldenScrew @singhranbir @Abdo2021-a What is the branch/ release of wiki that you are trying to install?

I just use instruction on main page https://github.com/frappe/wiki

**Comment by hasnain2808** [comment]
> > @techseria @GoldenScrew @singhranbir @Abdo2021-a What is the branch/ release of wiki that you are trying to install?
> 
> I just used instruction on main page [frappe/wiki](https://github.com/frappe/wiki)
> 
Updated the instructions in there 

> I can't understand what do you want? Can we use wiki now with version-13 ERPNext?

Wiki master will not work on frappe v13 it is for frappe develop
There was a branch called version-13 that was created as an experiment. But it is not getting any new features.

**Comment by saru2020** [comment]
i'm also facing this issue, should i use this branch('version-13)?

**Comment by saru2020** [comment]
> https://github.com/frappe/wiki/blob/82c4b64aa6582a4abc52fe38766bf5e4b428db07/wiki/wiki/doctype/wiki_sidebar/wiki_sidebar.py#L14
> 
> This should be changed to `get_all`. @hasnain2808
> 
> `pluck` doesn't exist on v13

is this the only change required for the fix? @ankush 

after applying the mentioned change/fix, I'm facing this error:

```
Installing wiki...

Updating DocTypes for wiki          : [========================================] 100%

Traceback (most recent call last):

  File "/home/frappe/frappe-bench/commands/new.py", line 132, in <module>

    main()

  File "/home/frappe/frappe-bench/commands/new.py", line 62, in main

    _new_site(

  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 81, in _new_site

    install_app(app, verbose=verbose, set_as_patched=not source_sql)

  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 172, in install_app

    frappe.get_attr(after_install)()

  File "/home/frappe/frappe-bench/apps/wiki/wiki/install.py", line 22, in after_install

    sidebar.insert()

  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 240, in insert

    self.run_before_save_methods()

  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 972, in run_before_save_methods

    self.run_method("before_save")

  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 869, in run_method

    out = Document.hook(fn)(self, *args, **kwargs)

  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1161, in composer

    return composed(self, method, *args, **kwargs)

  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1144, in runner

    add_to_return_value(self, fn(self, *args, **kwargs))

  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 863, in <lambda>

    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)

  File "/home/frappe/frappe-bench/apps/wiki/wiki/wiki/doctype/wiki_sidebar/wiki_sidebar.py", line 14, in before_save

    details = frappe.db.get_all('Wiki Sidebar',

  File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 540, in get_all

    return frappe.get_all(*args, **kwargs)

  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1475, in get_all

    return get_list(doctype, *args, **kwargs)

  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1448, in get_list

    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)

TypeError: execute() got an unexpected keyword argument 'fieldname'
```

anything else that I should be doing?

note: I'm installing via frappe docker

**Comment by ankush** [comment]
Using version-13 branch is only option. There are other breaking changes too which require version-14 (develop)

**Comment by codezart** [comment]
@[techseria](https://github.com/techseria) so what is the conclusion?

**Comment by techseria** [comment]
We have uninstalled the wiki app. Instead of that we are using wikijs and planning to integrate wikijs with erpnext through custom app.

**Comment by nikoma** [comment]
Does it mean the the wiki app will be discontinued? It seemed very promising.

**Comment by karanwilson** [comment]
> Using version-13 branch is only option. There are other breaking changes too which require version-14 (develop)
> 
> Alternatively start using v14 beta fire

Dear @ankush , I am using v14, but the sidebar hierarchy is not working - is there something extra we need to do to achieve the sidebar hierarchy in Frappe v14..?
