### ISSUE TITLE
Permission (User-/Team restrictions)

### ISSUE THREAD

**Issue by dgram** [frappe/wiki#68]
Hey

i don't know if its the best place to write about these, but i don't know where to ask for them.

I doesnt seen anything about wiki pages and permissions, it would be pretty nice to i.e. restrict pages (and sub-pages) for (i.e. with erpnext) to specific departments / teams.

regards

**Comment by hasnain2808** [comment]
Similar to https://github.com/frappe/wiki/issues/60
