### ISSUE TITLE
attachment dropdown doesn't autohide

### ISSUE THREAD

**Issue by ankush** [frappe/wiki#73]
<img width="928" alt="Screenshot 2022-02-08 at 6 24 51 PM" src="https://user-images.githubusercontent.com/9079960/152991235-cb31562f-0d80-4139-a093-04cfa5bd9fc3.png">

usually fine but in some cases blocks other operations. 🥲

**Comment by hasnain2808** [comment]
Tried solving this some time back, Something wrong with the bootstrap event that hides it when out of focus. It is not getting setup. Marking it as a bug now.

**Comment by hasnain2808** [comment]
> usually fine but in some cases blocks other operations. 🥲

It is never fine😅
