### ISSUE TITLE
Not able to manage the position of a sidebar within another sidebar

### ISSUE THREAD

**Issue by hcsm-rafiei** [frappe/wiki#83]
If I add another sidebar within a sidebar frappe while automatically put it under all pages and won´t allow me to put it between two pages. 
Is there a way to put 1.3_Sidebar between 1.1_Page and 1.2_Page ?
Example:
1_Sidebar
- 1.1_Page
- 1.2_Page 
- 1.3_Sidebar   

2_Sidebar 
....

**Comment by hasnain2808** [comment]
It is not possible to order sidebars and pages in a mixed fashion. 
Currently, the order of pages and sidebars are maintained separately.
