### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by hans-permana** [frappe/wiki#98]
Hi Frappe team,

Good product! Would it be possible to add a conversion to PDF functionality? The use case is that writing a Minutes of Meeting in Wiki using Markdown and convert it to PDF to be sent to all meeting participants (external). This is to avoid having to write the same information twice.

Thanks,
Hans

**Comment by ankush** [comment]
You can print as PDF? 

Wiki pages are available on backend too where you can specify custom print format if you want to.
